name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  view-context:
    runs-on: ubuntu-latest
    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  add-to-linear:
    name: Add issue to Linear
    runs-on: ubuntu-latest
    steps:
      - uses: jamesacklin/linear-app-create-issue-action@v2
        with:
          issueTitle: ${{ github.event.issue.title }}
          issueContent: ${{ github.event.issue.body }}
          issueReporter: ${{ github.event.issue.user.login }}
          issueUrl: ${{ github.event.issue.html_url }}
          apiKey: ${{ secrets.LINEAR_APIKEY }}
          teamId: ${{ secrets.LINEAR_TEAMID }}
          stateId: ${{ secrets.LINEAR_STATEID }}
